import type { ChatThread, Interview, Job, UserProfile } from './types'

export const SKILL_POOL = [
  'React',
  'TypeScript',
  'Node.js',
  'Python',
  'SQL',
  'Project Management',
  'Arabic',
  'English',
  'Sales',
  'Marketing',
  'Figma',
  'Data Analysis',
  'Customer Service',
  'Accounting',
  'AutoCAD',
  'Civil Engineering',
  'Nursing',
  'Leadership',
  'Cloud / AWS',
  'Cybersecurity',
]

export const defaultProfile: UserProfile = {
  name: '',
  headline: '',
  avatar: '',
  city: 'riyadh',
  skills: [],
  experience: 'mid',
  desiredSalary: 12000,
  jobTypes: ['full_time', 'remote'],
  careerGoal: '',
  aspirationalSkills: [],
}

export const jobs: Job[] = [
  {
    id: 'j1',
    title: { en: 'Senior Frontend Engineer', ar: 'مهندس واجهات أمامية أول' },
    company: { en: 'Tamkeen Digital', ar: 'تمكين الرقمية' },
    logo: '',
    city: { en: 'Riyadh', ar: 'الرياض' },
    region: 'riyadh',
    type: 'full_time',
    experience: 'senior',
    salaryMin: 18000,
    salaryMax: 26000,
    skills: ['React', 'TypeScript', 'Node.js', 'Cloud / AWS'],
    description: {
      en: 'Lead the frontend for a Vision 2030 fintech platform serving millions across the Kingdom.',
      ar: 'قُد تطوير الواجهات لمنصة تقنية مالية ضمن رؤية 2030 تخدم الملايين في المملكة.',
    },
    verified: true,
    postedDaysAgo: 2,
    remoteFriendly: true,
  },
  {
    id: 'j2',
    title: { en: 'Product Designer', ar: 'مصمم منتجات' },
    company: { en: 'Noon', ar: 'نون' },
    logo: '',
    city: { en: 'Riyadh', ar: 'الرياض' },
    region: 'riyadh',
    type: 'full_time',
    experience: 'mid',
    salaryMin: 14000,
    salaryMax: 20000,
    skills: ['Figma', 'English', 'Leadership'],
    description: {
      en: 'Design delightful shopping experiences for the region’s leading e-commerce app.',
      ar: 'صمّم تجارب تسوّق مميزة لأبرز تطبيق تجارة إلكترونية في المنطقة.',
    },
    verified: true,
    postedDaysAgo: 1,
    remoteFriendly: false,
  },
  {
    id: 'j3',
    title: { en: 'Data Analyst', ar: 'محلل بيانات' },
    company: { en: 'stc', ar: 'إس تي سي' },
    logo: '',
    city: { en: 'Riyadh', ar: 'الرياض' },
    region: 'riyadh',
    type: 'full_time',
    experience: 'junior',
    salaryMin: 10000,
    salaryMax: 15000,
    skills: ['SQL', 'Python', 'Data Analysis', 'English'],
    description: {
      en: 'Turn telecom data into insights that shape national connectivity strategy.',
      ar: 'حوّل بيانات الاتصالات إلى رؤى تصنع استراتيجية الاتصال الوطنية.',
    },
    verified: true,
    postedDaysAgo: 4,
    remoteFriendly: true,
  },
  {
    id: 'j4',
    title: { en: 'Civil Site Engineer', ar: 'مهندس موقع مدني' },
    company: { en: 'NEOM', ar: 'نيوم' },
    logo: '',
    city: { en: 'Tabuk', ar: 'تبوك' },
    region: 'madinah',
    type: 'contract',
    experience: 'mid',
    salaryMin: 16000,
    salaryMax: 22000,
    skills: ['Civil Engineering', 'AutoCAD', 'Project Management'],
    description: {
      en: 'Build the future at one of the world’s most ambitious giga-projects.',
      ar: 'ابنِ المستقبل في أحد أكثر المشاريع العملاقة طموحًا في العالم.',
    },
    verified: true,
    postedDaysAgo: 6,
    remoteFriendly: false,
  },
  {
    id: 'j5',
    title: { en: 'Cloud Solutions Architect', ar: 'مهندس حلول سحابية' },
    company: { en: 'Saudi Aramco', ar: 'أرامكو السعودية' },
    logo: '',
    city: { en: 'Dhahran', ar: 'الظهران' },
    region: 'eastern',
    type: 'full_time',
    experience: 'senior',
    salaryMin: 22000,
    salaryMax: 32000,
    skills: ['Cloud / AWS', 'Cybersecurity', 'Leadership', 'Python'],
    description: {
      en: 'Architect secure, large-scale cloud platforms for global energy operations.',
      ar: 'صمّم منصات سحابية آمنة وواسعة النطاق لعمليات الطاقة العالمية.',
    },
    verified: true,
    postedDaysAgo: 3,
    remoteFriendly: false,
  },
  {
    id: 'j6',
    title: { en: 'Marketing Specialist', ar: 'أخصائي تسويق' },
    company: { en: 'Jahez', ar: 'جاهز' },
    logo: '',
    city: { en: 'Jeddah', ar: 'جدة' },
    region: 'makkah',
    type: 'full_time',
    experience: 'junior',
    salaryMin: 8000,
    salaryMax: 12000,
    skills: ['Marketing', 'Arabic', 'English', 'Data Analysis'],
    description: {
      en: 'Grow our brand across the Kingdom with creative, data-driven campaigns.',
      ar: 'نمِّ علامتنا في المملكة عبر حملات إبداعية قائمة على البيانات.',
    },
    verified: false,
    postedDaysAgo: 8,
    remoteFriendly: true,
  },
  {
    id: 'j7',
    title: { en: 'Registered Nurse', ar: 'ممرض مسجل' },
    company: { en: 'King Faisal Specialist Hospital', ar: 'مستشفى الملك فيصل التخصصي' },
    logo: '',
    city: { en: 'Riyadh', ar: 'الرياض' },
    region: 'riyadh',
    type: 'full_time',
    experience: 'mid',
    salaryMin: 12000,
    salaryMax: 18000,
    skills: ['Nursing', 'Customer Service', 'English', 'Arabic'],
    description: {
      en: 'Deliver world-class patient care at a leading specialist hospital.',
      ar: 'قدّم رعاية عالمية المستوى في مستشفى تخصصي رائد.',
    },
    verified: true,
    postedDaysAgo: 5,
    remoteFriendly: false,
  },
  {
    id: 'j8',
    title: { en: 'Backend Engineer', ar: 'مهندس خلفية' },
    company: { en: 'Lean Technologies', ar: 'لين' },
    logo: '',
    city: { en: 'Remote', ar: 'عن بعد' },
    region: 'remote',
    type: 'remote',
    experience: 'mid',
    salaryMin: 15000,
    salaryMax: 23000,
    skills: ['Node.js', 'TypeScript', 'SQL', 'Cloud / AWS'],
    description: {
      en: 'Build the open-banking infrastructure powering MENA fintech.',
      ar: 'ابنِ بنية الخدمات المصرفية المفتوحة التي تشغّل التقنية المالية بالمنطقة.',
    },
    verified: true,
    postedDaysAgo: 1,
    remoteFriendly: true,
  },
  {
    id: 'j9',
    title: { en: 'Accountant', ar: 'محاسب' },
    company: { en: 'Almarai', ar: 'المراعي' },
    logo: '',
    city: { en: 'Riyadh', ar: 'الرياض' },
    region: 'riyadh',
    type: 'full_time',
    experience: 'junior',
    salaryMin: 7000,
    salaryMax: 11000,
    skills: ['Accounting', 'SQL', 'Arabic'],
    description: {
      en: 'Manage financial reporting for the region’s largest food company.',
      ar: 'أدر التقارير المالية لأكبر شركة أغذية في المنطقة.',
    },
    verified: false,
    postedDaysAgo: 10,
    remoteFriendly: false,
  },
  {
    id: 'j10',
    title: { en: 'Cybersecurity Analyst', ar: 'محلل أمن سيبراني' },
    company: { en: 'Saudi National Bank', ar: 'البنك الأهلي السعودي' },
    logo: '',
    city: { en: 'Jeddah', ar: 'جدة' },
    region: 'makkah',
    type: 'full_time',
    experience: 'mid',
    salaryMin: 16000,
    salaryMax: 24000,
    skills: ['Cybersecurity', 'Cloud / AWS', 'Python', 'English'],
    description: {
      en: 'Protect the Kingdom’s largest bank from evolving digital threats.',
      ar: 'احمِ أكبر بنك في المملكة من التهديدات الرقمية المتطورة.',
    },
    verified: true,
    postedDaysAgo: 2,
    remoteFriendly: false,
  },
  {
    id: 'j11',
    title: { en: 'Software Engineering Intern', ar: 'متدرب هندسة برمجيات' },
    company: { en: 'SDAIA', ar: 'سدايا' },
    logo: '',
    city: { en: 'Riyadh', ar: 'الرياض' },
    region: 'riyadh',
    type: 'internship',
    experience: 'entry',
    salaryMin: 4000,
    salaryMax: 6000,
    skills: ['Python', 'Data Analysis', 'English'],
    description: {
      en: 'Kickstart your AI career at the national authority for data & AI.',
      ar: 'ابدأ مسيرتك في الذكاء الاصطناعي لدى الهيئة الوطنية للبيانات والذكاء الاصطناعي.',
    },
    verified: true,
    postedDaysAgo: 7,
    remoteFriendly: false,
  },
  {
    id: 'j12',
    title: { en: 'Engineering Manager', ar: 'مدير هندسة' },
    company: { en: 'Tabby', ar: 'تابي' },
    logo: '',
    city: { en: 'Remote', ar: 'عن بعد' },
    region: 'remote',
    type: 'remote',
    experience: 'lead',
    salaryMin: 28000,
    salaryMax: 40000,
    skills: ['Leadership', 'Node.js', 'Cloud / AWS', 'Project Management'],
    description: {
      en: 'Lead high-performing teams building the region’s top BNPL platform.',
      ar: 'قُد فرقًا عالية الأداء تبني أبرز منصة دفع آجل في المنطقة.',
    },
    verified: true,
    postedDaysAgo: 3,
    remoteFriendly: true,
  },
]

export function getJob(id: string) {
  return jobs.find((j) => j.id === id)
}

// Seeded chat threads (keyed by jobId) used once a user applies/messages.
export function seedThread(job: Job): ChatThread {
  return {
    jobId: job.id,
    companyName: job.company,
    jobTitle: job.title,
    logo: job.logo,
    messages: [
      {
        id: `${job.id}-m1`,
        from: 'them',
        at: Date.now() - 1000 * 60 * 60,
        text: {
          en: `Hi! Thanks for applying to the ${job.title.en} role. Your profile looks like a strong match. Are you open to a quick chat?`,
          ar: `مرحبًا! شكرًا لتقديمك على وظيفة ${job.title.ar}. ملفك يبدو متطابقًا بقوة. هل أنت متاح لمحادثة سريعة؟`,
        },
      },
    ],
  }
}

export const sampleInterview = (job: Job): Interview => ({
  id: `${job.id}-iv`,
  jobId: job.id,
  jobTitle: job.title,
  company: job.company,
  logo: job.logo,
  date: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3).toISOString().slice(0, 10),
  time: '11:00',
  mode: 'video',
  status: 'proposed',
})

const dayFromNow = (n: number) =>
  new Date(Date.now() + 1000 * 60 * 60 * 24 * n).toISOString().slice(0, 10)

// Offered interview times used by the chat scheduler + interviews screen.
export const interviewSlots: { date: string; time: string }[] = [
  { date: dayFromNow(2), time: '10:00' },
  { date: dayFromNow(2), time: '14:30' },
  { date: dayFromNow(3), time: '11:00' },
  { date: dayFromNow(4), time: '09:30' },
  { date: dayFromNow(5), time: '13:00' },
  { date: dayFromNow(6), time: '16:00' },
]
