import type { LocalizedText } from '@/lib/types'

export const hrModulesDict: Record<string, LocalizedText> = {
  // Common
  allDepartments: { en: 'All Departments', ar: 'جميع الأقسام' },
  illustrativeNotice: {
    en: 'Illustrative Saudi Labor Law calculation — for simulation purposes only.',
    ar: 'حسابات استرشادية وفق نظام العمل السعودي — لأغراض المحاكاة فقط.',
  },
  days: { en: 'days', ar: 'أيام' },
  day: { en: 'day', ar: 'يوم' },
  pendingApproval: { en: 'Pending Approval', ar: 'بانتظار الموافقة' },
  approved: { en: 'Approved', ar: 'معتمد' },
  rejected: { en: 'Rejected', ar: 'مرفوض' },
  active: { en: 'Active', ar: 'نشط' },
  completed: { en: 'Completed', ar: 'مكتمل' },
  saveChanges: { en: 'Save changes', ar: 'حفظ التغييرات' },
  cancel: { en: 'Cancel', ar: 'إلغاء' },
  close: { en: 'Close', ar: 'إغلاق' },

  // 1. Time Off Hub
  timeOffTitle: { en: 'Time Off & Leave Management', ar: 'إدارة الإجازات والغياب' },
  timeOffSubtitle: {
    en: 'Saudi Labor Law Article 109 accruals, public holidays, approval queue, and Ramadan work hours.',
    ar: 'استحقاقات الإجازات وفق المادة ١٠٩ من نظام العمل، والعطلات الرسمية، وسجل الموافقات، وساعات رمضان.',
  },
  requestTimeOff: { en: 'Request leave', ar: 'طلب إجازة' },
  leaveBalances: { en: 'Leave Balances', ar: 'أرصدة الإجازات' },
  pendingQueue: { en: 'Pending Requests', ar: 'الطلبات المعلقة' },
  pendingApprovalsQueue: { en: 'Pending approvals', ar: 'طلبات في انتظار الموافقة' },
  employeeBalancesRoster: { en: 'Employee leave balances', ar: 'أرصدة إجازات الموظفين' },
  officialHolidaysTab: { en: 'Official public holidays', ar: 'العطلات الرسمية المعتمدة' },
  teamCalendar: { en: 'Holiday & Leave Calendar', ar: 'تقويم العطلات والإجازات' },
  ramadanModeTitle: { en: 'Ramadan Reduced Hours', ar: 'ساعات العمل المخفضة في رمضان' },
  ramadanModeDesc: {
    en: 'Saudi Labor Law Article 98 sets working hours to 6 hours per day (36 hours weekly) for Muslim employees during Ramadan.',
    ar: 'تنص المادة ٩٨ من نظام العمل على تخفيض ساعات العمل اليومية إلى ٦ ساعات (٣٦ ساعة أسبوعياً) للمسلمين في شهر رمضان.',
  },
  ramadanActiveBadge: { en: 'Ramadan 6-Hour Schedule Active', ar: 'نظام ٦ ساعات مفعل حالياً' },
  ramadanStandardBadge: { en: 'Standard 8-Hour Schedule', ar: 'نظام الدوام الاعتيادي (٨ ساعات)' },
  annualLeaveArticle109Note: {
    en: 'Labor Law Art. 109: 21 days annual leave increases to 30 days upon completing 5 consecutive years of service.',
    ar: 'المادة ١٠٩: تزداد الإجازة السنوية من ٢١ إلى ٣٠ يوماً لمن أمضى خمس سنوات متصلة في خدمة صاحب العمل.',
  },
  tenureOver5Years: { en: '5+ years tenure (30 days tier)', ar: 'أكثر من ٥ سنوات خدمة (فئة ٣٠ يوماً)' },
  tenureUnder5Years: { en: '< 5 years tenure (21 days tier)', ar: 'أقل من ٥ سنوات خدمة (فئة ٢١ يوماً)' },
  approveRequest: { en: 'Approve', ar: 'موافقة' },
  rejectRequest: { en: 'Reject', ar: 'رفض' },
  leaveType: { en: 'Leave Type', ar: 'نوع الإجازة' },
  startDate: { en: 'Start Date', ar: 'تاريخ البدء' },
  endDate: { en: 'End Date', ar: 'تاريخ الانتهاء' },
  workingDaysCount: { en: 'Business Days (excl. Fri/Sat)', ar: 'أيام العمل (باستثناء الجمعة والسبت)' },
  leaveReason: { en: 'Reason / Notes', ar: 'سبب الإجازة / ملاحظات' },
  submitLeaveRequest: { en: 'Submit request', ar: 'تقديم الطلب' },
  availableBalance: { en: 'Available', ar: 'المتاح' },
  usedBalance: { en: 'Used', ar: 'المستهلك' },
  statutoryAllowance: { en: 'Annual Allowance', ar: 'الرصيد السنوي' },
  publicHolidays2026: { en: 'Official Saudi Public Holidays', ar: 'العطلات الرسمية في المملكة' },
  hijriApproximateNote: {
    en: 'Islamic Eid dates are governed by astronomical moon sightings and may vary by 1–2 days.',
    ar: 'مواعيد الأعياد الإسلامية تعتمد على الرؤية الشرعية للهلال وقد تختلف بيوم أو يومين.',
  },

  // 2. Onboarding Hub
  onboardingTitle: { en: 'New Hire Onboarding', ar: 'متابعة مباشرة وتأهيل الموظفين' },
  onboardingSubtitle: {
    en: 'Track new joiner checklists, Qiwa digital contract signing, CCHI insurance enrollment, and workstation setups.',
    ar: 'متابعة مهام التعيين الجديد، وتوثيق عقود قوى، وإصدار بطاقات التأمين، وتجهيز متطلبات العمل.',
  },
  activeNewHires: { en: 'Active Onboarding Hires', ar: 'الموظفون قيد التأهيل والمباشرة' },
  viewOfferLetter: { en: 'Preview Offer Letter', ar: 'معاينة خطاب العرض الوظيفي' },
  signOfferLetter: { en: 'Simulate Candidate e-Signature', ar: 'محاكاة التوقيع الرقمي للمرشح' },
  offerLetterTitle: { en: 'Bilingual Saudi Employment Offer', ar: 'خطاب العرض الوظيفي الثنائي المعتمد' },
  offerLetterDisclaimer: {
    en: 'Standard bilingual employment offer in accordance with Saudi Labor Law terms.',
    ar: 'عرض عمل ثنائي معتمد وفق ضوابط نظام العمل السعودي الموحد.',
  },
  checklistHr: { en: 'HR & Contracts', ar: 'الموارد البشرية والعقود' },
  checklistIt: { en: 'IT & Systems Access', ar: 'التقنية وحسابات النظام' },
  checklistDocs: { en: 'Compliance & Verification', ar: 'الوثائق والتحقق النظامي' },
  checklistTeam: { en: 'Department Orientation', ar: 'الاندماج وفريق العمل' },
  markCompleted: { en: 'Complete Onboarding', ar: 'إتمام المباشرة وتفعيل الموظف' },
  onboardingCompletedSuccess: {
    en: 'Onboarding completed! Employee status updated to Active and synced with payroll.',
    ar: 'تم إتمام المباشرة بنجاح! تم تحديث حالة الموظف إلى نشط وربطه بنظام الرواتب.',
  },
  taskOwner: { en: 'Assigned to', ar: 'المسؤول' },
  taskDueDate: { en: 'Due date', ar: 'تاريخ الاستحقاق' },

  // 3. Benefits & EOSB Hub
  benefitsTitle: { en: 'Benefits & End-of-Service (EOSB)', ar: 'المزايا ومكافأة نهاية الخدمة' },
  benefitsSubtitle: {
    en: 'CCHI medical insurance categories and Saudi Labor Law Article 84/85 statutory calculator.',
    ar: 'فئات التأمين الطبي المعتمدة من مجلس الضمان الصحي، وحاسبة مكافأة نهاية الخدمة للمادتين ٨٤ و ٨٥.',
  },
  cchiTiersTitle: { en: 'CCHI Medical Insurance Coverage', ar: 'فئات التأمين الصحي المعتمدة (CCHI)' },
  cchiTiersDesc: {
    en: 'Standardized insurance tiers covering healthcare networks, deductibles, and family dependents.',
    ar: 'الفئات المعتمدة لدى شركات التأمين (بوبا والتعاونية) شاملة التغطيات وشبكات المستشفيات والتحمل.',
  },
  eosbCalcTitle: { en: 'End-of-Service Benefit (EOSB) Calculator', ar: 'حاسبة مكافأة نهاية الخدمة (نظام العمل)' },
  eosbCalcDesc: {
    en: 'Official statutory formula under Articles 84 & 85 of the Saudi Labor Law.',
    ar: 'الاحتساب النظامي المعتمد وفق المادتين ٨٤ و ٨٥ من نظام العمل السعودي.',
  },
  selectEmployee: { en: 'Select employee to calculate', ar: 'اختر موظفاً لاحتساب مكافأته' },
  customCalculation: { en: 'Custom simulation', ar: 'محاكاة مخصصة' },
  tenureDuration: { en: 'Length of Service', ar: 'مدة الخدمة' },
  yearsLabel: { en: 'years', ar: 'سنوات' },
  monthsLabel: { en: 'months', ar: 'أشهر' },
  daysLabel: { en: 'days', ar: 'أيام' },
  monthlyWageBase: { en: 'Statutory Wage Base (Basic + Housing)', ar: 'الأجر المعتمد (الأساسي + بدل السكن)' },
  separationReason: { en: 'Separation Reason', ar: 'سبب انتهاء العلاقة العمالية' },
  reasonResignation: { en: 'Resignation (Article 85)', ar: 'استقالة العامل (المادة ٨٥)' },
  reasonContractExpiry: { en: 'Fixed-term Contract Expiration', ar: 'انتهاء مدة العقد محدد المدة' },
  reasonTermination: { en: 'Termination by Employer / Non-renewal', ar: 'إنهاء العقد من قبل المنشأة' },
  reasonForceMajeure: { en: 'Force Majeure / Mutual Agreement', ar: 'قوة قاهرة / اتفاق الطرفين' },
  article84BaseAward: { en: 'Article 84 Base Entitlement', ar: 'استحقاق المادة ٨٤ الأساسي' },
  article84Tier1: { en: 'First 5 years (1/2 month per year)', ar: 'السنوات الخمس الأولى (نصف راتب/سنة)' },
  article84Tier2: { en: 'Years beyond 5 (Full month per year)', ar: 'السنوات التالية (راتب شهر كامل/سنة)' },
  article85Multiplier: { en: 'Article 85 Resignation Multiplier', ar: 'نسبة الاستحقاق في حال الاستقالة (م ٨٥)' },
  payableEosbAmount: { en: 'Total Estimated EOSB Award', ar: 'صافي مكافأة نهاية الخدمة التقديرية' },
  eosbLegalNotice: {
    en: 'Statutory Note: Under Article 85, resignation yields 0 for < 2 yrs service, 1/3 for 2–5 yrs, 2/3 for 5–10 yrs, and full award for 10+ yrs.',
    ar: 'تنبيه نظامي: بموجب المادة ٨٥، لا يستحق العامل مكافأة إذا استقال قبل سنتين، ويستحق الثلث من سنتين إلى ٥، والثلثين من ٥ إلى ١٠، والمكافأة كاملة بعد ١٠ سنوات.',
  },
  tierVip: { en: 'VIP Executive', ar: 'فئة كبار التنفيذيين (VIP)' },
  tierClassA: { en: 'Class A Premier', ar: 'الفئة أ (Class A)' },
  tierClassB: { en: 'Class B Standard', ar: 'الفئة ب (Class B)' },
  tierClassC: { en: 'Class C Essential', ar: 'الفئة ج (Class C)' },
  networkHospital: { en: 'Approved Hospital Network', ar: 'شبكة المستشفيات المعتمدة' },
  maxCoverageLimit: { en: 'Annual Max Coverage', ar: 'الحد الأقصى للتغطية السنوية' },
  copayDeductible: { en: 'Outpatient Co-pay', ar: 'نسبة التحمل للعيادات الخارجية' },

  // 4. Performance Hub
  performanceTitle: { en: 'Performance & Goals', ar: 'إدارة الأداء والأهداف' },
  performanceSubtitle: {
    en: 'Lightweight quarterly OKRs, review cycles, and 1–5 competency assessments.',
    ar: 'أهداف ربع سنوية، ودورات تقييم الأداء، ومقياس الكفاءات من ١ إلى ٥.',
  },
  currentReviewCycle: { en: 'Current Cycle: Q3 2026 Mid-Year Review', ar: 'الدورة الحالية: التقييم النصف سنوي للربع الثالث ٢٠٢٦' },
  overallRating: { en: 'Rating (1 to 5)', ar: 'التقييم العام (من ١ إلى ٥)' },
  smartGoalsTitle: { en: 'Quarterly SMART Goals', ar: 'أهداف الربع الحالية' },
  goalProgress: { en: 'Progress', ar: 'نسبة الإنجاز' },
  managerFeedback: { en: 'Manager Notes & Development Feedback', ar: 'ملاحظات وتوجيهات المدير' },
  addGoal: { en: 'Add Goal', ar: 'إضافة هدف' },
  submitReview: { en: 'Save Review', ar: 'حفظ التقييم' },
  ratingScale1: { en: '1 - Needs Improvement', ar: '١ - يحتاج إلى تحسين' },
  ratingScale2: { en: '2 - Developing', ar: '٢ - في طور التطور' },
  ratingScale3: { en: '3 - Meets Expectations', ar: '٣ - يحقق التوقعات' },
  ratingScale4: { en: '4 - Exceeds Expectations', ar: '٤ - يتجاوز التوقعات' },
  ratingScale5: { en: '5 - Outstanding', ar: '٥ - أداء استثنائي' },

  // 5. Reports (iHR Vision) Hub
  reportsTitle: { en: 'iHR Vision — Analytics & Reports', ar: 'رؤية iHR — التحليلات والتقارير' },
  reportsSubtitle: {
    en: 'Executive workforce intelligence: Headcount trends, department cost breakdown, and Nitaqat trajectory.',
    ar: 'لوحة التحليلات التنفيذية: نمو الكادر البشري، وتوزيع تكاليف الرواتب، ومسار التوطين ونطاقات.',
  },
  headcountGrowth: { en: 'Headcount Trajectory (6 Months)', ar: 'تطور عدد الموظفين (٦ أشهر)' },
  departmentPayrollCost: { en: 'Monthly Payroll by Department', ar: 'توزيع كتلة الأجور الشهرية حسب القسم' },
  saudizationTrend: { en: 'Saudization & Platinum Target', ar: 'مسار التوطين نحو النطاق البلاتيني' },
  leaveUtilizationRate: { en: 'Leave Utilization Rate', ar: 'معدل استهلاك الإجازات' },
  totalActiveStaff: { en: 'Total Workforce', ar: 'إجمالي القوى العاملة' },
  totalMonthlyPayrollCost: { en: 'Monthly Employer Cost', ar: 'التكلفة الإجمالية للأجور' },
  currentSaudizationPct: { en: 'Current Saudization', ar: 'نسبة التوطين الحالية' },
  targetPlatinumRate: { en: 'Platinum Minimum', ar: 'الحد الأدنى للبلاتيني' },
}
