import { daysFromToday } from './dates'
import type { Applicant } from './types'

export function createHiringSeed(): Applicant[] {
  return [
    // --- J1: Senior Frontend Engineer (Riyadh, 18-26k SAR, React, TypeScript, Node.js, Cloud / AWS) ---
    {
      id: 'app-01',
      jobId: 'j1',
      name: { en: 'Sultan Al-Ghamdi', ar: 'سلطان الغامدي' },
      headline: { en: 'Senior Frontend Architect | React & TypeScript', ar: 'مهندس واجهات أمامية أول | React و TypeScript' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'male',
      skills: ['React', 'TypeScript', 'Node.js', 'Cloud / AWS', 'Leadership'],
      experience: 'senior',
      expectedSalary: 24000,
      stage: 'applied',
      appliedAt: daysFromToday(-2),
      source: 'app',
      email: 'sultan.ghamdi@example.com',
      phone: '+966 50 112 3456',
      cvSummary: {
        en: '6+ years leading modern React and Next.js applications in Riyadh fintechs. Strong architectural background in micro-frontends and AWS cloud CI/CD.',
        ar: 'أكثر من ٦ سنوات خبرة في قيادة تطبيقات React و Next.js في شركات التقنية المالية بالرياض. خبرة معمارية واسعة في البنى الحديثة والسحابية.',
      },
      notes: [
        {
          id: 'n-01',
          author: 'Noura Al-Harbi',
          text: 'Top candidate from iHR Jobs swipe app. Excellent GitHub portfolio.',
          createdAt: daysFromToday(-1),
        },
      ],
    },
    {
      id: 'app-02',
      jobId: 'j1',
      name: { en: 'Laila Al-Mansoor', ar: 'ليلى المنصور' },
      headline: { en: 'Frontend Engineer | Web & Design Systems', ar: 'مهندسة واجهات أمامية | نظم التصميم والويب' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'female',
      skills: ['React', 'TypeScript', 'Figma', 'English'],
      experience: 'mid',
      expectedSalary: 19000,
      stage: 'screening',
      appliedAt: daysFromToday(-5),
      source: 'app',
      email: 'laila.mansoor@example.com',
      phone: '+966 55 234 5678',
      cvSummary: {
        en: '4 years experience building enterprise design systems and web apps in React and TypeScript.',
        ar: '٤ سنوات خبرة في بناء نظم التصميم المؤسسية وتطبيقات الويب باستخدام React و TypeScript.',
      },
      notes: [
        {
          id: 'n-02',
          author: 'Noura Al-Harbi',
          text: 'Passed initial recruiter phone screen. Highly articulate.',
          createdAt: daysFromToday(-3),
        },
      ],
    },
    {
      id: 'app-03',
      jobId: 'j1',
      name: { en: 'Tareq Al-Balawi', ar: 'طارق البلوي' },
      headline: { en: 'Full Stack Developer | React & Node.js', ar: 'مطور واجهات وخلفيات | React و Node.js' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'male',
      skills: ['React', 'Node.js', 'SQL', 'TypeScript'],
      experience: 'senior',
      expectedSalary: 23000,
      stage: 'interview',
      appliedAt: daysFromToday(-9),
      source: 'linkedin',
      email: 'tareq.balawi@example.com',
      phone: '+966 54 345 6789',
      cvSummary: {
        en: '7 years building high-throughput consumer web platforms. Experienced in Node.js backend microservices and React web portals.',
        ar: '٧ سنوات في تطوير منصات الويب عالية الاستخدام. خبرة في الخدمات الخلفية Node.js وبوابات React.',
      },
      notes: [
        {
          id: 'n-03',
          author: 'Rajesh Kumar',
          text: 'Technical interview went great. Clean code and strong system architecture skills.',
          createdAt: daysFromToday(-4),
        },
      ],
    },
    {
      id: 'app-04',
      jobId: 'j1',
      name: { en: 'Zaid Khaleel', ar: 'زيد خليل' },
      headline: { en: 'Lead Web Engineer', ar: 'مهندس ويب قيادي' },
      city: 'riyadh',
      nationality: 'JO',
      gender: 'male',
      skills: ['React', 'TypeScript', 'Node.js', 'Cloud / AWS', 'Project Management'],
      experience: 'lead',
      expectedSalary: 25000,
      stage: 'offer',
      appliedAt: daysFromToday(-18),
      source: 'referral',
      email: 'zaid.khaleel@example.com',
      phone: '+966 56 456 7890',
      cvSummary: {
        en: '8+ years engineering leadership across top Tier-1 Saudi digital products. Led engineering teams of 12+ developers.',
        ar: 'أكثر من ٨ سنوات قيادة تقنية في منتجات رقمية كبرى بالمملكة. قاد فرقاً هندسية تضم أكثر من ١٢ مطوراً.',
      },
      notes: [
        {
          id: 'n-04',
          author: 'Noura Al-Harbi',
          text: 'Formal offer sent at 25k SAR/mo. Awaiting final acceptance.',
          createdAt: daysFromToday(-2),
        },
      ],
    },
    {
      id: 'app-05',
      jobId: 'j1',
      name: { en: 'Mohannad Al-Subaie', ar: 'مهند السبيعي' },
      headline: { en: 'Junior Frontend Developer', ar: 'مطور واجهات أمامية مبتدئ' },
      city: 'jeddah',
      nationality: 'SA',
      gender: 'male',
      skills: ['React', 'Arabic', 'English'],
      experience: 'junior',
      expectedSalary: 12000,
      stage: 'applied',
      appliedAt: daysFromToday(-1),
      source: 'app',
      email: 'mohannad.subaie@example.com',
      phone: '+966 50 567 8901',
      cvSummary: {
        en: 'Recent CS graduate with passionate frontend bootcamp experience and 2 personal React projects.',
        ar: 'خريج علوم حاسب حديث بخبرة معسكرات برمجية ومشروعين عمليين في React.',
      },
      notes: [],
    },
    {
      id: 'app-06',
      jobId: 'j1',
      name: { en: 'Hamza Farooq', ar: 'حمزة فاروق' },
      headline: { en: 'Web Developer | PHP & JavaScript', ar: 'مطور ويب | PHP و JavaScript' },
      city: 'dammam',
      nationality: 'PK',
      gender: 'male',
      skills: ['SQL', 'English'],
      experience: 'mid',
      expectedSalary: 15000,
      stage: 'rejected',
      appliedAt: daysFromToday(-12),
      source: 'direct',
      email: 'hamza.farooq@example.com',
      phone: '+966 53 678 9012',
      cvSummary: {
        en: 'Web developer focused on legacy PHP CMS setups. Limited TypeScript or modern React ecosystem experience.',
        ar: 'مطور ويب متخصص في أنظمة إدارة المحتوى القديمة، خبرة محدودة في بيئة React الحديثة و TypeScript.',
      },
      notes: [
        {
          id: 'n-06',
          author: 'Noura Al-Harbi',
          text: 'Does not meet the React/TypeScript requirements for a Senior role.',
          createdAt: daysFromToday(-10),
        },
      ],
    },

    // --- J2: Product Designer (Riyadh, 14-20k SAR, Figma, English, Leadership) ---
    {
      id: 'app-07',
      jobId: 'j2',
      name: { en: 'Reem Al-Qahtani', ar: 'ريم القحطاني' },
      headline: { en: 'Senior UX/UI Designer | Design Systems', ar: 'مصممة تجربة وواجهة مستخدم أولى | نظم التصميم' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'female',
      skills: ['Figma', 'English', 'Leadership', 'Arabic'],
      experience: 'mid',
      expectedSalary: 18000,
      stage: 'screening',
      appliedAt: daysFromToday(-4),
      source: 'app',
      email: 'reem.qahtani@example.com',
      phone: '+966 50 789 0123',
      cvSummary: {
        en: '5 years crafting mobile and web user experiences for Saudi e-commerce and SaaS platforms. Extensive Figma library mastery.',
        ar: '٥ سنوات في تصميم تجارب المستخدم لتطبيقات التجارة الإلكترونية وحلول SaaS بالمملكة. احتراف كامل لمكتبات Figma.',
      },
      notes: [
        {
          id: 'n-07',
          author: 'Noura Al-Harbi',
          text: 'Stunning portfolio. Clean typography and Arabic RTL mastery.',
          createdAt: daysFromToday(-2),
        },
      ],
    },
    {
      id: 'app-08',
      jobId: 'j2',
      name: { en: 'Bandar Al-Olayan', ar: 'بندر العليان' },
      headline: { en: 'Product & Visual Designer', ar: 'مصمم منتجات وتصميم بصري' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'male',
      skills: ['Figma', 'English', 'Marketing'],
      experience: 'mid',
      expectedSalary: 16000,
      stage: 'applied',
      appliedAt: daysFromToday(-1),
      source: 'app',
      email: 'bandar.olayan@example.com',
      phone: '+966 55 890 1234',
      cvSummary: {
        en: 'Passionate digital product designer with 3 years of agency experience delivering polished consumer UIs.',
        ar: 'مصمم منتجات رقمية بخبرة ٣ سنوات في الوكالات الإعلانية وتصميم واجهات المستخدم الرقمية.',
      },
      notes: [],
    },
    {
      id: 'app-09',
      jobId: 'j2',
      name: { en: 'Nouf Al-Shehri', ar: 'نوف الشهري' },
      headline: { en: 'Lead UX Researcher & Designer', ar: 'قائدة أبحاث وتصميم تجربة المستخدم' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'female',
      skills: ['Figma', 'Leadership', 'English', 'Project Management'],
      experience: 'senior',
      expectedSalary: 20000,
      stage: 'interview',
      appliedAt: daysFromToday(-8),
      source: 'linkedin',
      email: 'nouf.shehri@example.com',
      phone: '+966 54 901 2345',
      cvSummary: {
        en: '7 years leading user research and end-to-end design for digital banking and logistics platforms in Riyadh.',
        ar: '٧ سنوات في قيادة أبحاث المستخدمين والتصميم المتكامل للمنصات المصرفية واللوجستية في الرياض.',
      },
      notes: [
        {
          id: 'n-09',
          author: 'Abdulrahman Al-Qahtani',
          text: 'Impressive presentation on user journey mapping for enterprise clients.',
          createdAt: daysFromToday(-3),
        },
      ],
    },
    {
      id: 'app-10',
      jobId: 'j2',
      name: { en: 'Hiba Tariq', ar: 'هبة طارق' },
      headline: { en: 'Graphic & UI Designer', ar: 'مصممة جرافيك وواجهات' },
      city: 'jeddah',
      nationality: 'EG',
      gender: 'female',
      skills: ['Figma', 'Arabic'],
      experience: 'junior',
      expectedSalary: 11000,
      stage: 'applied',
      appliedAt: daysFromToday(-2),
      source: 'app',
      email: 'hiba.tariq@example.com',
      phone: '+966 56 012 3456',
      cvSummary: {
        en: '2 years working on social media assets and basic UI prototyping. Eager to specialize in full product design.',
        ar: 'سنتان خبرة في التصاميم الترويجية ونماذج الواجهات الأولية، شغوفة بالتخصص في تصميم المنتجات.',
      },
      notes: [],
    },
    {
      id: 'app-11',
      jobId: 'j2',
      name: { en: 'Khaled Al-Garni', ar: 'خالد القرني' },
      headline: { en: 'Senior Product Designer', ar: 'مصمم منتجات أول' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'male',
      skills: ['Figma', 'English', 'Leadership', 'Data Analysis'],
      experience: 'senior',
      expectedSalary: 19500,
      stage: 'hired',
      appliedAt: daysFromToday(-22),
      source: 'referral',
      email: 'khaled.garni@example.com',
      phone: '+966 50 123 4567',
      cvSummary: {
        en: '6 years crafting enterprise portals and consumer apps. Strong expertise in design tokens, component architecture, and usability testing.',
        ar: '٦ سنوات في تصميم البوابات المؤسسية وتطبيقات المستهلكين. تخصص في نظم التصميم واختبارات قابلية الاستخدام.',
      },
      notes: [
        {
          id: 'n-11',
          author: 'Noura Al-Harbi',
          text: 'Offer accepted! Contract signed through Qiwa. Starting onboarding next week.',
          createdAt: daysFromToday(-5),
        },
      ],
    },

    // --- J3: Data Analyst (Riyadh, 10-15k SAR, SQL, Python, Data Analysis, English) ---
    {
      id: 'app-12',
      jobId: 'j3',
      name: { en: 'Mansour Al-Mutawa', ar: 'منصور المطوع' },
      headline: { en: 'Business Intelligence & Data Analyst', ar: 'محلل بيانات وذكاء أعمال' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'male',
      skills: ['SQL', 'Python', 'Data Analysis', 'English'],
      experience: 'junior',
      expectedSalary: 12500,
      stage: 'interview',
      appliedAt: daysFromToday(-7),
      source: 'app',
      email: 'mansour.mutawa@example.com',
      phone: '+966 55 234 5679',
      cvSummary: {
        en: '2.5 years transforming inventory and sales data into executive Power BI dashboards. Advanced SQL querying and Python pandas scripts.',
        ar: 'سنتان ونصف في تحويل بيانات المبيعات والمخزون إلى لوحات معلومات تنفيذية. احتراف استعلامات SQL ومكتبات Python.',
      },
      notes: [
        {
          id: 'n-12',
          author: 'Faisal Al-Otaibi',
          text: 'Very sharp on financial models and SQL optimizations. Recommend for offer.',
          createdAt: daysFromToday(-2),
        },
      ],
    },
    {
      id: 'app-13',
      jobId: 'j3',
      name: { en: 'Sarah Al-Gosaibi', ar: 'سارة القصيبي' },
      headline: { en: 'Data Analyst | Tableau & SQL', ar: 'محللة بيانات | Tableau و SQL' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'female',
      skills: ['SQL', 'Data Analysis', 'English', 'Arabic'],
      experience: 'junior',
      expectedSalary: 11000,
      stage: 'applied',
      appliedAt: daysFromToday(-1),
      source: 'app',
      email: 'sarah.gosaibi@example.com',
      phone: '+966 54 345 6780',
      cvSummary: {
        en: 'Recent honors graduate in Information Systems with 1 year internship analyzing retail supply chain trends.',
        ar: 'خريجة نظم معلومات بمرتبة الشرف مع سنة تدريب عملي في تحليل بيانات سلاسل الإمداد.',
      },
      notes: [],
    },
    {
      id: 'app-14',
      jobId: 'j3',
      name: { en: 'Rakan Al-Sharif', ar: 'راكان الشريف' },
      headline: { en: 'Operations Data Analyst', ar: 'محلل بيانات عمليات' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'male',
      skills: ['SQL', 'Python', 'Data Analysis', 'Project Management'],
      experience: 'mid',
      expectedSalary: 14500,
      stage: 'screening',
      appliedAt: daysFromToday(-4),
      source: 'linkedin',
      email: 'rakan.sharif@example.com',
      phone: '+966 56 456 7891',
      cvSummary: {
        en: '4 years analyzing supply chain turnaround times and warehouse throughput for wholesale distributors.',
        ar: '٤ سنوات في تحليل أوقات استجابة سلاسل الإمداد ومعدلات تشغيل المستودعات لشركات الجملة.',
      },
      notes: [
        {
          id: 'n-14',
          author: 'Noura Al-Harbi',
          text: 'Direct industry match with our wholesale logistics business.',
          createdAt: daysFromToday(-2),
        },
      ],
    },
    {
      id: 'app-15',
      jobId: 'j3',
      name: { en: 'Fahad Al-Malki', ar: 'فهد المالكي' },
      headline: { en: 'Data & Reporting Specialist', ar: 'أخصائي بيانات وتقارير' },
      city: 'dammam',
      nationality: 'SA',
      gender: 'male',
      skills: ['SQL', 'Accounting'],
      experience: 'junior',
      expectedSalary: 9500,
      stage: 'applied',
      appliedAt: daysFromToday(-3),
      source: 'app',
      email: 'fahad.malki@example.com',
      phone: '+966 50 567 8902',
      cvSummary: {
        en: 'Accounting graduate with strong Excel and intermediate SQL skills. Seeking full data analyst role.',
        ar: 'خريج محاسبة بمهارات متقدمة في Excel ومهارات متوسطة في SQL. يتطلع للانتقال لمجال تحليل البيانات.',
      },
      notes: [],
    },
    {
      id: 'app-16',
      jobId: 'j3',
      name: { en: 'Dina Al-Husseini', ar: 'دينا الحسيني' },
      headline: { en: 'Senior Analytics Consultant', ar: 'مستشارة تحليلات متقدمة' },
      city: 'riyadh',
      nationality: 'JO',
      gender: 'female',
      skills: ['SQL', 'Python', 'Data Analysis', 'Leadership', 'English'],
      experience: 'senior',
      expectedSalary: 22000,
      stage: 'rejected',
      appliedAt: daysFromToday(-14),
      source: 'direct',
      email: 'dina.husseini@example.com',
      phone: '+966 53 678 9013',
      cvSummary: {
        en: '8 years leading corporate analytics. Over-qualified for this Junior/Mid requisition, salary expectation exceeds budget.',
        ar: '٨ سنوات في قيادة التحليلات المؤسسية. مؤهلاتها تتجاوز متطلبات هذه الوظيفة وراتبها المتوقع يتجاوز الميزانية.',
      },
      notes: [
        {
          id: 'n-16',
          author: 'Noura Al-Harbi',
          text: 'Senior profile; budget capped at 15k SAR. Archived for future Lead opening.',
          createdAt: daysFromToday(-11),
        },
      ],
    },

    // --- J6: Marketing Specialist (Jeddah/Riyadh, 8-12k SAR, Marketing, Arabic, English, Data Analysis) ---
    {
      id: 'app-17',
      jobId: 'j6',
      name: { en: 'Joud Al-Harbi', ar: 'جود الحربي' },
      headline: { en: 'Digital Marketing & Content Specialist', ar: 'أخصائية تسويق رقمي ومحتوى' },
      city: 'jeddah',
      nationality: 'SA',
      gender: 'female',
      skills: ['Marketing', 'Arabic', 'English', 'Data Analysis'],
      experience: 'junior',
      expectedSalary: 10500,
      stage: 'offer',
      appliedAt: daysFromToday(-11),
      source: 'app',
      email: 'joud.harbi@example.com',
      phone: '+966 50 789 0124',
      cvSummary: {
        en: '3 years orchestrating social campaigns, performance ad spend, and brand copywriting for Saudi retail brands in Jeddah.',
        ar: '٣ سنوات في إدارة الحملات الرقمية، الإعلانات الممولة، وكتابة المحتوى لعلامات تجارية سعودية في جدة.',
      },
      notes: [
        {
          id: 'n-17',
          author: 'Khalid Al-Shehri',
          text: 'Superb communication skills. Offer extended for Jeddah branch.',
          createdAt: daysFromToday(-1),
        },
      ],
    },
    {
      id: 'app-18',
      jobId: 'j6',
      name: { en: 'Waleed Al-Bishi', ar: 'وليد البيشي' },
      headline: { en: 'Growth Marketing & Campaign Executive', ar: 'تنفيذي تسويق نمو وحملات' },
      city: 'jeddah',
      nationality: 'SA',
      gender: 'male',
      skills: ['Marketing', 'Arabic', 'Data Analysis', 'Sales'],
      experience: 'junior',
      expectedSalary: 9500,
      stage: 'screening',
      appliedAt: daysFromToday(-3),
      source: 'app',
      email: 'waleed.bishi@example.com',
      phone: '+966 55 890 1235',
      cvSummary: {
        en: '2 years executing B2B email marketing, influencer partnerships, and lead generation in the western province.',
        ar: 'سنتان في التسويق للشركات، الشراكات التسويقية، وتوليد العملاء المحتملين بالمنطقة الغربية.',
      },
      notes: [],
    },
    {
      id: 'app-19',
      jobId: 'j6',
      name: { en: 'Amina Sayed', ar: 'أمينة سيد' },
      headline: { en: 'Brand Strategist & Copywriter', ar: 'مخططة علامة تجارية وكاتبة محتوى' },
      city: 'jeddah',
      nationality: 'EG',
      gender: 'female',
      skills: ['Marketing', 'Arabic', 'English'],
      experience: 'junior',
      expectedSalary: 11000,
      stage: 'applied',
      appliedAt: daysFromToday(-1),
      source: 'app',
      email: 'amina.sayed@example.com',
      phone: '+966 54 901 2346',
      cvSummary: {
        en: 'Creative marketing specialist with bilingual campaign execution experience for FMCG brands in Saudi Arabia.',
        ar: 'أخصائية تسويق إبداعي بخبرة تنفيذ حملات باللغتين للسلع الاستهلاكية في المملكة.',
      },
      notes: [],
    },
    {
      id: 'app-20',
      jobId: 'j6',
      name: { en: 'Saud Al-Homaidan', ar: 'سعود الحميدان' },
      headline: { en: 'Social Media & Community Coordinator', ar: 'منسق شبكات اجتماعية ومجتمع' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'male',
      skills: ['Marketing', 'Arabic'],
      experience: 'junior',
      expectedSalary: 8500,
      stage: 'applied',
      appliedAt: daysFromToday(-2),
      source: 'app',
      email: 'saud.homaidan@example.com',
      phone: '+966 56 012 3457',
      cvSummary: {
        en: '1.5 years managing brand accounts on X, TikTok, and Instagram with high community engagement metrics.',
        ar: 'سنة ونصف في إدارة حسابات العلامات التجارية على إكس وتيك توك وإنستغرام.',
      },
      notes: [],
    },
    {
      id: 'app-21',
      jobId: 'j6',
      name: { en: 'Nasser Al-Dossary', ar: 'ناصر الدوسري' },
      headline: { en: 'Senior Commercial Director', ar: 'مدير تجاري أول' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'male',
      skills: ['Sales', 'Leadership'],
      experience: 'senior',
      expectedSalary: 28000,
      stage: 'rejected',
      appliedAt: daysFromToday(-16),
      source: 'direct',
      email: 'nasser.dossary@example.com',
      phone: '+966 50 123 4568',
      cvSummary: {
        en: 'Commercial executive. Mismatched profile for a specialist level marketing requisition.',
        ar: 'مسؤول تنفيذي تجاري. غير متطابق مع متطلبات وظيفة أخصائي تسويق ميداني.',
      },
      notes: [],
    },

    // --- J8: Backend Engineer (Remote / Riyadh, 15-23k SAR, Node.js, TypeScript, SQL, Cloud / AWS) ---
    {
      id: 'app-22',
      jobId: 'j8',
      name: { en: 'Abdullah Al-Kindi', ar: 'عبدالله الكندي' },
      headline: { en: 'Senior Backend Engineer | Node.js & Cloud', ar: 'مهندس خلفية أول | Node.js والسحابة' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'male',
      skills: ['Node.js', 'TypeScript', 'SQL', 'Cloud / AWS', 'Python'],
      experience: 'senior',
      expectedSalary: 21000,
      stage: 'screening',
      appliedAt: daysFromToday(-3),
      source: 'app',
      email: 'abdullah.kindi@example.com',
      phone: '+966 55 234 5680',
      cvSummary: {
        en: '6 years designing fault-tolerant payment processors and REST/GraphQL APIs on AWS microservices with Node.js and PostgreSQL.',
        ar: '٦ سنوات في بناء معالجات الدفع المقاومة للأعطال وواجهات برمجة التطبيقات على خوادم AWS و PostgreSQL.',
      },
      notes: [
        {
          id: 'n-22',
          author: 'Rajesh Kumar',
          text: 'Superb architecture experience with financial systems. Scheduling interview.',
          createdAt: daysFromToday(-1),
        },
      ],
    },
    {
      id: 'app-23',
      jobId: 'j8',
      name: { en: 'Kareem Al-Sayed', ar: 'كريم السيد' },
      headline: { en: 'Backend Systems Developer | Node.js', ar: 'مطور نظم خلفية | Node.js' },
      city: 'riyadh',
      nationality: 'EG',
      gender: 'male',
      skills: ['Node.js', 'SQL', 'TypeScript'],
      experience: 'mid',
      expectedSalary: 17000,
      stage: 'applied',
      appliedAt: daysFromToday(-1),
      source: 'app',
      email: 'kareem.sayed@example.com',
      phone: '+966 54 345 6781',
      cvSummary: {
        en: '3.5 years developing backends for logistics tracking and ERP integrations across the GCC.',
        ar: '٣ سنوات ونصف في تطوير الأنظمة الخلفية لتتبع الخدمات اللوجستية وتكاملات أنظمة ERP.',
      },
      notes: [],
    },
    {
      id: 'app-24',
      jobId: 'j8',
      name: { en: 'Yasmeen Al-Nader', ar: 'ياسمين النادر' },
      headline: { en: 'Cloud & API Engineer', ar: 'مهندسة سحابية وواجهات برمجة' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'female',
      skills: ['Node.js', 'TypeScript', 'Cloud / AWS', 'SQL', 'English'],
      experience: 'mid',
      expectedSalary: 18500,
      stage: 'interview',
      appliedAt: daysFromToday(-7),
      source: 'linkedin',
      email: 'yasmeen.nader@example.com',
      phone: '+966 56 456 7892',
      cvSummary: {
        en: '4 years specializing in serverless architecture, AWS Lambda, DynamoDB, and robust API security.',
        ar: '٤ سنوات في البنى السحابية الحديثة، خدمات AWS بدون خوادم، وأمان واجهات التطبيقات.',
      },
      notes: [
        {
          id: 'n-24',
          author: 'Rajesh Kumar',
          text: 'Great round 1 interview. Hands-on coding assessment was top tier.',
          createdAt: daysFromToday(-3),
        },
      ],
    },
    {
      id: 'app-25',
      jobId: 'j8',
      name: { en: 'Faris Al-Ghamdi', ar: 'فارس الغامدي' },
      headline: { en: 'Software Engineer | Python & Django', ar: 'مهندس برمجيات | Python و Django' },
      city: 'dammam',
      nationality: 'SA',
      gender: 'male',
      skills: ['Python', 'SQL', 'English'],
      experience: 'junior',
      expectedSalary: 12000,
      stage: 'applied',
      appliedAt: daysFromToday(-2),
      source: 'app',
      email: 'faris.ghamdi@example.com',
      phone: '+966 50 567 8903',
      cvSummary: {
        en: '2 years backend development experience in Python and PostgreSQL. Interested in transitioning to Node.js/TypeScript.',
        ar: 'سنتان في التطوير الخلفي باستخدام Python و PostgreSQL، يتطلع للتعمق في بيئة Node.js.',
      },
      notes: [],
    },
    {
      id: 'app-26',
      jobId: 'j8',
      name: { en: 'Othman Al-Hajri', ar: 'عثمان الهاجري' },
      headline: { en: 'Full Stack Engineer | Node.js & React', ar: 'مهندس برمجيات شامل | Node.js و React' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'male',
      skills: ['Node.js', 'TypeScript', 'React', 'SQL', 'Cloud / AWS'],
      experience: 'mid',
      expectedSalary: 19000,
      stage: 'applied',
      appliedAt: daysFromToday(-1),
      source: 'app',
      email: 'othman.hajri@example.com',
      phone: '+966 53 678 9014',
      cvSummary: {
        en: '4 years building full stack web applications with emphasis on resilient backend architecture and real-time websockets.',
        ar: '٤ سنوات في بناء تطبيقات الويب المتكاملة مع التركيز على مرونة الأنظمة الخلفية والاتصال الحي.',
      },
      notes: [],
    },
    {
      id: 'app-27',
      jobId: 'j8',
      name: { en: 'Mustafa Al-Basha', ar: 'مصطفى الباشا' },
      headline: { en: 'Backend Infrastructure Specialist', ar: 'أخصائي بنية تحتية وخلفية' },
      city: 'riyadh',
      nationality: 'EG',
      gender: 'male',
      skills: ['Node.js', 'TypeScript', 'SQL', 'Cloud / AWS', 'Cybersecurity'],
      experience: 'senior',
      expectedSalary: 22500,
      stage: 'hired',
      appliedAt: daysFromToday(-30),
      source: 'referral',
      email: 'mustafa.basha@example.com',
      phone: '+966 50 789 0125',
      cvSummary: {
        en: '7 years building secure banking gateways and high-throughput data sync services across GCC financial institutions.',
        ar: '٧ سنوات في تطوير بوابات الدفع البنكية الآمنة وخدمات مزامنة البيانات عالية الكثافة.',
      },
      notes: [
        {
          id: 'n-27',
          author: 'Noura Al-Harbi',
          text: 'Offer accepted. Already progressing in employee onboarding checklist.',
          createdAt: daysFromToday(-7),
        },
      ],
    },

    // Additional fresh inbound candidates for recruiter swipe testing:
    {
      id: 'app-28',
      jobId: 'j1',
      name: { en: 'Bayan Al-Zahrani', ar: 'بيان الزهراني' },
      headline: { en: 'Frontend Engineer | Next.js & React', ar: 'مهندسة واجهات أمامية | Next.js و React' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'female',
      skills: ['React', 'TypeScript', 'Node.js', 'English'],
      experience: 'mid',
      expectedSalary: 18500,
      stage: 'applied',
      appliedAt: daysFromToday(0),
      source: 'app',
      email: 'bayan.zahrani@example.com',
      phone: '+966 55 890 1236',
      cvSummary: {
        en: '3.5 years developing accessible, responsive Next.js web applications with high Core Web Vitals scores.',
        ar: '٣ سنوات ونصف في تطوير تطبيقات Next.js سريعة ومتوافقة مع أعلى معايير أداء الويب.',
      },
      notes: [],
    },
    {
      id: 'app-29',
      jobId: 'j1',
      name: { en: 'Anas Al-Najjar', ar: 'أنس النجار' },
      headline: { en: 'Web Application Developer', ar: 'مطور تطبيقات ويب' },
      city: 'riyadh',
      nationality: 'SY',
      gender: 'male',
      skills: ['React', 'TypeScript', 'Cloud / AWS'],
      experience: 'senior',
      expectedSalary: 23500,
      stage: 'applied',
      appliedAt: daysFromToday(0),
      source: 'app',
      email: 'anas.najjar@example.com',
      phone: '+966 54 901 2347',
      cvSummary: {
        en: '6 years engineering enterprise React portals with seamless AWS micro-service integrations.',
        ar: '٦ سنوات في تطوير بوابات React للشركات الكبرى وربطها بالخدمات السحابية.',
      },
      notes: [],
    },
    {
      id: 'app-30',
      jobId: 'j2',
      name: { en: 'Hussam Al-Dakhil', ar: 'حسام الداخل' },
      headline: { en: 'Product Designer & Design Strategist', ar: 'مصمم منتجات واستراتيجي تصميم' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'male',
      skills: ['Figma', 'Leadership', 'English', 'Arabic'],
      experience: 'mid',
      expectedSalary: 17500,
      stage: 'applied',
      appliedAt: daysFromToday(0),
      source: 'app',
      email: 'hussam.dakhil@example.com',
      phone: '+966 56 012 3458',
      cvSummary: {
        en: '4 years designing engaging fintech flows for Saudi consumers. Strong background in Figma design systems.',
        ar: '٤ سنوات في تصميم مسارات وتجارب التقنية المالية للمستخدمين في المملكة.',
      },
      notes: [],
    },
    {
      id: 'app-31',
      jobId: 'j3',
      name: { en: 'Maram Al-Amoudi', ar: 'مرام العمودي' },
      headline: { en: 'Junior Data Scientist & Analyst', ar: 'عالمة ومحللة بيانات مبتدئة' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'female',
      skills: ['Python', 'SQL', 'Data Analysis', 'English'],
      experience: 'junior',
      expectedSalary: 11500,
      stage: 'applied',
      appliedAt: daysFromToday(0),
      source: 'app',
      email: 'maram.amoudi@example.com',
      phone: '+966 50 123 4569',
      cvSummary: {
        en: 'Recent MS graduate in Data Analytics with hands-on predictive modeling and SQL dashboarding projects.',
        ar: 'حاصلة على ماجستير تحليلات بيانات مع مشاريع عملية في النماذج التنبؤية واستعلامات SQL.',
      },
      notes: [],
    },
    {
      id: 'app-32',
      jobId: 'j8',
      name: { en: 'Ibrahim Al-Rashoud', ar: 'إبراهيم الرشود' },
      headline: { en: 'Backend Engineer | Cloud Native APIs', ar: 'مهندس خلفية | واجهات برمجية سحابية' },
      city: 'riyadh',
      nationality: 'SA',
      gender: 'male',
      skills: ['Node.js', 'SQL', 'TypeScript', 'Cloud / AWS'],
      experience: 'mid',
      expectedSalary: 18000,
      stage: 'applied',
      appliedAt: daysFromToday(0),
      source: 'app',
      email: 'ibrahim.rashoud@example.com',
      phone: '+966 55 234 5681',
      cvSummary: {
        en: '4 years architecting resilient REST APIs, microservices, and database indexing for high traffic web apps.',
        ar: '٤ سنوات في تصميم واجهات REST المعيارية، والخدمات المصغرة، وفهرسة قواعد البيانات للأنظمة النشطة.',
      },
      notes: [],
    },
  ]
}
